---
- name: Deploy a web page using Apache with handlers
  hosts: kali
  become: yes

  tasks:
    - name: Install Apache web server
      apt:
        name: apache2
        state: present
        update_cache: no

    - name: Ensure Apache service is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Deploy custom index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head><title>Welcome</title></head>
          <body>
            <h1>This page is deployed by Ansible using a handler!</h1>
          </body>
          </html>
        owner: www-data
        group: www-data
        mode: '0644'
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted

