---
- name: Create directory /oppt/demo with permission 755
  hosts: all
  become: yes

  tasks:
    - name: Create /oppt/demo directory
      file:
        path: /oppt/demo
        state: directory
        mode: '0755'

