apiVersion: v1
kind: Pod
metadata:
  name: log-writer
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "while true; do date >> /data/log.txt; sleep 5; done"]
    volumeMounts:
    - mountPath: /data
      name: log-storage
  volumes:
  - name: log-storage
    persistentVolumeClaim:
      claimName: my-pvc

