apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-app
  template:
    metadata:
      labels:
        app: secret-app
    spec:
      containers:
        - name: demo-container
          image: nginx
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-date
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-date
                  key: DB_PASSWORD

