apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker
        image: busybox
        command: ["sh", "-c", "while true; do echo Hello from worker app; sleep 10; done"]

